version: "3"

services:

        ryzhikovvi-netology_db:
                image: postgres:latest
                container_name: ryzhikovvi-netology-db
                ports:
                        - 5432:5432
                volumes:
                        - ./pg_data:/var/lib/postgresql/data/pgdata
                environment:
                        POSTGRES_PASSWORD: ryzhikovvi12!3!!
                        POSTGRES_DB: ryzhikovvi-netology_db
                        PGDATA: /var/lib/postgresql/data/pgdata
                networks:
                        ryzhikovvi-my-netology-hw:
                                ipv4_address: 172.22.0.2
                restart: always


        pgadmin:
                image: dpage/pgadmin4
                links:
                        - ryzhikovvi-netology_db
                container_name: ryzhikovvi-pgadmin
                environment:
                        PGADMIN_DEFAULT_EMAIL: ryzhikovvi@mymail.me
                        PGADMIN_DEFAULT_PASSWORD: 123
                ports:
                        - "61231:80"
                networks:
                        ryzhikovvi-my-netology-hw:
                                ipv4_address: 172.22.0.3
                restart: always
                
                
        zabbix-server:
                image: zabbix/zabbix-server-pgsql
                links:
                        - ryzhikovvi-netology_db
                container_name: ryzhikovvi-zabbix-netology
                environment:
                        DB_SERVER_HOST: '172.22.0.2'
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: ryzhikovvi12!3!!
                ports:
                        - "10051:10051"
                networks:
                        ryzhikovvi-my-netology-hw:
                                ipv4_address: 172.22.0.4
                restart: always


        zabbix_wgui:
                image: zabbix/zabbix-web-apache-pgsql
                links:
                        - ryzhikovvi-netology_db
                        - zabbix-server
                container_name: netology_zabbix_wgui
                environment:
                        DB_SERVER_HOST: '172.22.0.2'
                        POSTGRES_USER: 'postgres'
                        POSTGRES_PASSWORD: ryzhikovvi12!3!!
                        ZBX_SERVER_HOST: "zabbix_wgui"
                        PHP_TZ: "Europe/Moscow"
                ports:
                        - "80:8080"
                        - "443:8443"
                networks:
                        ryzhikovvi-my-netology-hw:
                                ipv4_address: 172.22.0.5
                restart: always

networks:
        ryzhikovvi-my-netology-hw:
                driver: bridge
                ipam:
                        config:
                        - subnet: 172.22.0.0/24




